plugins:
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
  eslint:
    enabled: true
    channel: "eslint-6"

exclude_patterns:
  - node_modules/*
  - coverage/*
  - tests/fixture/*
  - package-lock.json
  - demo.gif
  - dist/*
  - tsconfig.json
  - qrscanner
  - .nyc_output
