plugins:
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
  eslint:
    enabled: true

exclude_patterns:
  - node_modules/*
  - coverage/*
  - tests/fixture/*
  - package-lock.json
  - demo.gif
